export const weddingData = {
  groom: {
    name: "Minh Khoa",
    fullName: "NGUYỄN MINH KHOA",
    nickname: "The Smash King",
    number: "09",
    position: "Chú Rể",
    stats: {
      age: "27",
      height: "178cm",
      sport: "Cầu Lông",
      club: "CLB Phú Thọ",
      achievement: "Á Quân Giải Quận 2022",
    },
  },
  bride: {
    name: "Thanh Vy",
    fullName: "TRẦN THANH VY",
    nickname: "The Drop Shot Queen",
    number: "17",
    position: "Cô Dâu",
    stats: {
      age: "25",
      height: "163cm",
      sport: "Cầu Lông",
      club: "CLB Phú Thọ",
      achievement: "Vô Địch Giải Quận 2021 & 2022",
    },
  },
  wedding: {
    dateDisplay: "18.04.2026",
    dateISO: "2026-04-18T10:30:00",
    dateTimestamp: new Date("2026-04-18T10:30:00").getTime(),
    dayOfWeek: "Thứ Bảy",
    ceremony: {
      time: "10:30 SA",
      venue: "Nhà Nguyện Dòng Chúa Cứu Thế",
      address: "38 Kỳ Đồng, P.9, Q.3, TP.HCM",
      icon: "⛪",
    },
    reception: {
      time: "11:30 SA",
      venue: "White Palace Convention Center",
      address: "194 Hoàng Văn Thụ, Phú Nhuận, TP.HCM",
      hall: "Crystal Hall - Tầng 2",
      icon: "🏛️",
    },
    afterparty: {
      time: "18:00 CH",
      venue: "Skybar Rooftop Lounge",
      address: "Tầng 25, Hotel des Arts, Q.3, TP.HCM",
      icon: "🥂",
    },
  },
  story: [
    {
      year: "2021",
      event: "FIRST SERVE",
      title: "Giao Cầu Định Mệnh",
      desc: "Lần đầu gặp nhau tại sân cầu lông Phú Thọ trong giải đấu CLB mùa hè. Khoa ấn tượng bởi pha drop shot hoàn hảo của Vy — một tình yêu bắt đầu từ... thua trận.",
      image: "/1.webp",
    },
    {
      year: "2022",
      event: "RALLY",
      title: "Những Buổi Tập Không Ngừng",
      desc: "Từ bạn cùng sân đến người đồng hành. Cùng nhau luyện tập sáng sớm, cùng thất bại và cùng đứng dậy. Tình cảm nảy sinh tự nhiên như một pha rally không hồi kết.",
      image: "/3.webp",
    },
    {
      year: "2023",
      event: "MATCH POINT",
      title: "Chính Thức Về Cùng Đội",
      desc: "Cặp đôi chính thức hẹn hò sau giải đôi nam nữ — nơi họ cùng nhau vô địch lần đầu. Chiếc cúp đó, và tình yêu đó, vẫn đang được giữ gìn cẩn thận.",
      image: "/5.webp",
    },
    {
      year: "2025",
      event: "CHAMPIONSHIP",
      title: "Cầu Hôn Tại Sân Đấu",
      desc: "Khoa cầu hôn Vy ngay tại vị trí sân cũ — nơi họ gặp nhau lần đầu. Anh đã 'cố tình' bỏ pha smash định mệnh đó. Vy nói có. Khoảnh khắc đẹp nhất career!",
      image: "/7.webp",
    },
  ],
  guestbook: [
    { id: 1, name: "Anh Tuấn & Chị Linh", message: "Chúc mừng hai bạn! Đây chắc chắn là match hay nhất trong career! 🏸", time: "2 giờ trước" },
    { id: 2, name: "Team CLB Phú Thọ", message: "Vô địch ngoài sân đấu là đủ rồi, giờ vô địch trong cuộc đời nữa nhé! 🏆", time: "3 giờ trước" },
    { id: 3, name: "Gia đình Bác Ba", message: "Cầu chúc hai con trăm năm hạnh phúc, mãi là đôi uyên ương xứng đôi vừa lứa!", time: "5 giờ trước" },
    { id: 4, name: "Bạn Minh Hiếu", message: "Game, Set and MATCH! Chúc mừng đôi bạn viết nên chương mới đẹp nhất! 💚", time: "1 ngày trước" },
    { id: 5, name: "Team Tennis Club SG", message: "From the court to forever! Congratulations Khoa & Vy! ❤️🏸", time: "1 ngày trước" },
    { id: 6, name: "Chị Phương Anh", message: "Chúc hai bạn luôn là đôi partner tuyệt vời nhất, trên sân và trong cuộc sống!", time: "2 ngày trước" },
    { id: 7, name: "Dì Tám", message: "Khoa à, bắt được người ngoan rồi nhé. Vy à, chịu đựng ảnh giỏi lắm! 😄💕", time: "2 ngày trước" },
    { id: 8, name: "Nhóm Kép Đôi", message: "Mixed doubles champions on court, and now life partners too! ✨🏆", time: "3 ngày trước" },
  ],
  photos: [
    { id: 1, src: "/1.webp", caption: "The Match Begins" },
    { id: 2, src: "/2.webp", caption: "Court Side Moments" },
    { id: 3, src: "/3.webp", caption: "Training Together" },
    { id: 4, src: "/4.webp", caption: "Victory Pose" },
    { id: 5, src: "/5.webp", caption: "Off Court Romance" },
    { id: 6, src: "/6.webp", caption: "Golden Hour" },
    { id: 7, src: "/7.webp", caption: "The Proposal" },
    { id: 8, src: "/8.webp", caption: "Championship Kiss" },
    { id: 9, src: "/9.webp", caption: "Game Set Match" },
    { id: 10, src: "/10.webp", caption: "Love Rally" },
    { id: 11, src: "/11.webp", caption: "Serve & Return" },
    { id: 12, src: "/12.webp", caption: "Net Play" },
    { id: 13, src: "/13.webp", caption: "Match Point" },
    { id: 14, src: "/14.webp", caption: "Final Set" },
    { id: 15, src: "/15.webp", caption: "Champions Together" },
    { id: 16, src: "/16.webp", caption: "Award Ceremony" },
    { id: 17, src: "/17.webp", caption: "Team Photo" },
    { id: 18, src: "/18.webp", caption: "After Party" },
    { id: 19, src: "/19.webp", caption: "Forever Teammates" },
    { id: 20, src: "/20.webp", caption: "The Grand Final" },
  ],
};

export type WeddingData = typeof weddingData;
